"""Regenerate research outputs and evidence. No novelty or validity certificate is implied."""
from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import os
from pathlib import Path
import platform
import unittest

import numpy as np
import scipy
import matplotlib

import mesh_methods as m2
import mesh_methods_3d as m3

ROOT = Path(__file__).resolve().parent
OUT = ROOT/'output/generated'
EVIDENCE = ROOT/'output/audit'


def finite_difference_check() -> list[dict]:
    checks = []
    # Test fixed seeds and explicitly stored coordinates, not an unknown historical run.
    for shape in ((5, 6, 7), (6, 6, 6)):
        boundary = m3.twisted_cube_boundary_3d() if shape[0] == 5 else m3.ball_boundary_3d()
        grid = m3.coons_patch_3d(boundary, *shape)
        rng = np.random.default_rng(22092026)
        grid[1:-1, 1:-1, 1:-1] += rng.normal(0, .001, grid[1:-1, 1:-1, 1:-1].shape)
        x = m3._pack_interior_3d(grid)
        indices = rng.choice(x.size, min(24, x.size), replace=False)
        funs = [('inverse_mean_ratio', lambda v: m3._winslow_objective_and_gradient_3d(v, grid))]
        for mu in (0, .01, .1, 1.0):
            funs.append((f'adaptive_mu_{mu:g}', lambda v, mu=mu: m3._adaptive_objective_and_gradient_3d(
                v, grid, m3.volume_3d(grid), orientation_barrier=mu)))
        for name, fun in funs:
            _, grad = fun(x)
            errors = []
            for i in indices:
                h = 1e-6
                xp, xm = x.copy(), x.copy(); xp[i] += h; xm[i] -= h
                fd = (fun(xp)[0]-fun(xm)[0])/(2*h)
                errors.append(abs(fd-grad[i])/max(1, abs(fd), abs(grad[i])))
            checks.append(dict(shape=shape, method=name, seed=22092026, h=1e-6,
                               coordinate_indices=indices.tolist(), max_scaled_error=max(errors)))
    if max(c['max_scaled_error'] for c in checks) > 1e-6:
        raise AssertionError('Finite-difference verification failed')
    return checks


def generate_discussion() -> None:
    rows = list(csv.DictReader((OUT/'results_3d.csv').open(encoding='utf-8-sig')))
    def row(domain: str, method: str) -> dict:
        return next(r for r in rows if r['domain'] == domain and r['method'].startswith(method))
    tw_m, tw_a = row('Скрученный куб', 'Mean'), row('Скрученный куб', 'Адаптивное')
    ba_m, ba_a = row('Шар', 'Mean'), row('Шар', 'Адаптивное')
    ar_m, ar_a = row('Арковая призма', 'Mean'), row('Арковая призма', 'Адаптивное')
    reduction = 100*(1-float(tw_a['volume_cv'])/float(tw_m['volume_cv']))
    def num(r, k): return f'{float(r[k]):.4f}'
    text = rf'''% Generated by audit_reproduce.py from results_3d.csv; do not hand-edit numbers.
В скрученном кубе адаптивный вариант при $\mu=0.1$ даёт
$CV_V={num(tw_a,'volume_cv')}$ против ${num(tw_m,'volume_cv')}$ у inverse mean ratio
(снижение на ${reduction:.1f}\,\%$). Значения ортогональности близки, но не тождественны:
${float(tw_a['orthogonality_score']):.6f}$ и ${float(tw_m['orthogonality_score']):.6f}$ соответственно.
В шаре inverse mean ratio имеет наибольший среди трёх методов
$Q_{{\rm orth}}={num(ba_m,'orthogonality_score')}$ и наименьший
$AR_{{95}}={num(ba_m,'aspect_p95')}$; адаптивный вариант даёт меньший разброс
объёмов: $CV_V={num(ba_a,'volume_cv')}$ против ${num(ba_m,'volume_cv')}$,
но уступает по ортогональности.

В арковой призме inverse mean ratio имеет наибольший $Q_{{\rm orth}}$ и
наибольшее значение минимального углового масштабированного якобиана, а также наименьшие $CV_V$ и $AR_{{95}}$
в проверенной тройке. Его $AR_{{95}}={num(ar_m,'aspect_p95')}$, тогда как для
адаптивного варианта $AR_{{95}}={num(ar_a,'aspect_p95')}$.
Однако по размерному показателю $\sigma_{{\rm len}}$ адаптивный вариант лучше:
${num(ar_a,'directional_length_difference')}$ против ${num(ar_m,'directional_length_difference')}$.
Поэтому превосходство по \emph{{всем}} метрикам не утверждается.
Это наблюдения при указанных разрешениях, границе, начальной сетке и параметрах,
а не универсальный рейтинг функционалов и не оценка ошибки решения уравнения.
'''
    (OUT/'discussion_3d.tex').write_text(text, encoding='utf-8')


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--full', action='store_true', help='Also regenerate 2D/3D numerical series and mu=0 control')
    args = parser.parse_args()
    os.chdir(ROOT); OUT.mkdir(parents=True, exist_ok=True); EVIDENCE.mkdir(parents=True, exist_ok=True)
    if args.full:
        m2.run_experiment(OUT)
        m2.run_adaptive_mu0_control(OUT)
        m3.run_experiment_3d(OUT)
    generate_discussion()
    checks = finite_difference_check()
    example = json.loads((ROOT/'tests/data/positive_corners_negative_sample.json').read_text())
    grid = np.asarray(example['grid'])
    controls = {}
    for balanced in (False, True):
        z = m3.generate_harmonic_3d(m3.arch_prism_boundary_3d(), 11, 11, 11, balance_stiffness=balanced)
        controls[str(balanced)] = dict(metrics=m3.grid_metrics_3d(z), parameters=z.parameters)
    suite = unittest.defaultTestLoader.discover(str(ROOT), pattern='test_*.py')
    stream = io.StringIO()
    test_result = unittest.TextTestRunner(stream=stream, verbosity=2).run(suite)
    (EVIDENCE/'tests.txt').write_text(stream.getvalue(), encoding='utf-8')
    payload = dict(
        base_main_commit='9b18165ba00d325bc98b9c9189cfba4efae2a0c6',
        python=platform.python_version(), platform=platform.platform(),
        numpy=np.__version__, scipy=scipy.__version__, matplotlib=matplotlib.__version__,
        threads={k: os.environ.get(k) for k in ('OPENBLAS_NUM_THREADS','OMP_NUM_THREADS')},
        tests_run=test_result.testsRun, tests_passed=test_result.wasSuccessful(),
        tests_executed=test_result.testsRun-len(test_result.skipped),
        tests_skipped=[dict(test=str(test),reason=reason) for test,reason in test_result.skipped],
        full_numerical_series_regenerated=bool(args.full),
        scope=('Full numerical series, gradients, saved-grid metrics and tests' if args.full else
               'Retained numerical series; rechecked gradients, controls, saved-grid metrics and tests'),
        finite_difference_checks=checks, unbalanced_balanced_prism_control=controls,
        corner_counterexample=dict(min_corner=m3.min_signed_jacobian_3d(grid),
                                   min_27_sample=float(np.min(m3.sampled_cell_min_jacobians(grid)))),
        source_sha256={p.relative_to(ROOT).as_posix():hashlib.sha256(p.read_bytes()).hexdigest()
                       for p in sorted(ROOT.glob('*.py'))},
    )
    (EVIDENCE/'verification.json').write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding='utf-8')
    maximum = max(c['max_scaled_error'] for c in checks)
    mantissa, exponent = f'{maximum:.2e}'.split('e')
    (OUT/'verification_numbers.tex').write_text(
        rf'\newcommand{{\AuditTestCount}}{{{test_result.testsRun}}}'+'\n'+
        r'\newcommand{\AuditGradientError}{'+mantissa+r'\cdot10^{'+str(int(exponent))+'}}\n', encoding='utf-8')
    print(f'Tests: {test_result.testsRun}, passed={test_result.wasSuccessful()}, max FD error={maximum:.4g}')
    if not test_result.wasSuccessful():
        raise SystemExit(stream.getvalue())


if __name__ == '__main__':
    main()
